from .models import (
    BaseModelWrapper,
    HookManager,
    TransformerWrapper,
    VisionWrapper,
    LinearProbe,
    MLPProbe,
    EnergyProbe,
    MahalanobisDetector,
    pool_representations,
)
from .steering import (
    SteeringVector,
    SteeringExtractor,
    MeanDiffExtractor,
    PCAExtractor,
    MassMeanExtractor,
    ProbeExtractor,
    extract_steering_vectors,
    BaseIntervener,
    AdditiveIntervener,
    OrthogonalProjectionIntervener,
    SubspaceClampingIntervener,
    GatedIntervener,
    LayerScheduler,
    TokenPositionScheduler,
)
from .data import (
    TextSample,
    ContrastivePair,
    BaseDataset,
    ContrastiveDataset,
    TextClassificationDataset,
    SyntheticVisionDataset,
    create_dataloader,
    text_collate_fn,
    contrastive_collate_fn,
    get_train_val_split,
    make_world,
    draw,
    splits,
)
from .training import (
    ContrastiveRepresentationLoss,
    EnergyMarginLoss,
    Trainer,
    ProbeTrainer,
)
from .evaluation import (
    compute_auroc,
    compute_fpr95,
    compute_aupr,
    compute_ece,
    compute_ood_metrics,
    OODEvaluator,
    SteeringEvaluator,
)
from .utils import (
    set_seed,
    get_device,
    to_device,
    clear_device_cache,
    get_logger,
    setup_logging,
    load_config,
    save_config,
    Config,
)

__version__ = "0.1.0"

__all__ = [
    # Models & Hooks
    "BaseModelWrapper",
    "HookManager",
    "TransformerWrapper",
    "VisionWrapper",
    "LinearProbe",
    "MLPProbe",
    "EnergyProbe",
    "MahalanobisDetector",
    "pool_representations",
    # Steering
    "SteeringVector",
    "SteeringExtractor",
    "MeanDiffExtractor",
    "PCAExtractor",
    "MassMeanExtractor",
    "ProbeExtractor",
    "extract_steering_vectors",
    "BaseIntervener",
    "AdditiveIntervener",
    "OrthogonalProjectionIntervener",
    "SubspaceClampingIntervener",
    "GatedIntervener",
    "LayerScheduler",
    "TokenPositionScheduler",
    # Data
    "TextSample",
    "ContrastivePair",
    "BaseDataset",
    "ContrastiveDataset",
    "TextClassificationDataset",
    "SyntheticVisionDataset",
    "create_dataloader",
    "text_collate_fn",
    "contrastive_collate_fn",
    "get_train_val_split",
    "make_world",
    "draw",
    "splits",
    # Training
    "ContrastiveRepresentationLoss",
    "EnergyMarginLoss",
    "Trainer",
    "ProbeTrainer",
    # Evaluation
    "compute_auroc",
    "compute_fpr95",
    "compute_aupr",
    "compute_ece",
    "compute_ood_metrics",
    "OODEvaluator",
    "SteeringEvaluator",
    # Utils
    "set_seed",
    "get_device",
    "to_device",
    "clear_device_cache",
    "get_logger",
    "setup_logging",
    "load_config",
    "save_config",
    "Config",
]
